<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
 ~ Copyright 2026 youngmonkeys.org
 ~ 
 ~ Licensed under the ezyplatform, Version 1.0.0 (the "License");
 ~ you may not use this file except in compliance with the License.
 ~ You may obtain a copy of the License at
 ~ 
 ~     https://youngmonkeys.org/licenses/ezyplatform-1.0.0.txt
 ~ 
 ~ Unless required by applicable law or agreed to in writing, software
 ~ distributed under the License is distributed on an "AS IS" BASIS,
 ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 ~ See the License for the specific language governing permissions and
 ~ limitations under the License.
--><project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.youngmonkeys</groupId>
        <artifactId>ezyplatform-parent</artifactId>
        <version>0.0.2</version>
    </parent>
    <artifactId>ezyvector</artifactId>
    <groupId>org.youngmonkeys</groupId>
    <version>0.0.1</version>
    <packaging>pom</packaging>

    <name>ezyvector</name>
    <description>ezyvector</description>

    <properties>
        <!--suppress UnresolvedMavenProperty -->
        <ezyplatform.home>${env.EZYPLATFORM_HOME}</ezyplatform.home>
    <ecommerce.version>1.3.5</ecommerce.version>
        <ezyaccount.version>0.1.9</ezyaccount.version>
        <ezyarticle.version>1.3.4</ezyarticle.version>
        <ezychat.version>0.1.2</ezychat.version>
        <ezycrm.version>0.5.1</ezycrm.version>
        <ezylogin.version>0.3.5</ezylogin.version>
        <ezymail.version>0.2.4</ezymail.version>
        <ezysupport.version>0.5.0</ezysupport.version>
        <facebook.client.version>2022.3.1</facebook.client.version>
        <google.apis.version>v2-rev157-1.25.0</google.apis.version>
        <google.client.version>1.33.2</google.client.version>
        <graphql.version>0.2.8</graphql.version>
        <javax.mail.version>1.6.2</javax.mail.version>
        <jsoup.version>1.18.3</jsoup.version>
        <pdfbox.version>2.0.31</pdfbox.version>
        <poi.version>5.2.5</poi.version>
        <socket.monitor.version>0.0.1</socket.monitor.version>
        <zxing.version>3.5.3</zxing.version>
        <ezyai.version>0.0.3</ezyai.version>
    </properties>

    <modules>
        <module>ezyvector-sdk</module>
        <module>ezyvector-socket-plugin</module>
        <module>ezyvector-admin-plugin</module>
        <module>ezyvector-web-plugin</module>
    </modules>

    <dependencies>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezyplatform-test-sdk</artifactId>
            <version>${ezy.platform.version}</version>
            <scope>test</scope>
        </dependency>
    <dependency>
            <groupId>com.google.zxing</groupId>
            <artifactId>javase</artifactId>
            <version>${zxing.version}</version>
        <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.sun.mail</groupId>
            <artifactId>javax.mail</artifactId>
            <version>${javax.mail.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.tvd12</groupId>
            <artifactId>ezyhttp-server-graphql</artifactId>
            <version>${ezy.http.version}</version>
        <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.tvd12</groupId>
            <artifactId>ezyhttp-server-thymeleaf</artifactId>
            <version>${ezy.http.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
            <version>${javax.servlet.version}</version>
            <optional>true</optional>
        <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.jsoup</groupId>
            <artifactId>jsoup</artifactId>
            <version>${jsoup.version}</version>
        <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ecommerce-sdk</artifactId>
            <version>${ecommerce.version}</version>
            <scope>system</scope>
            <systemPath>${ezyplatform.home}/web/plugins/ecommerce/lib/ecommerce-sdk-${ecommerce.version}.jar
            </systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezyarticle-sdk</artifactId>
            <version>${ezyarticle.version}</version>
            <scope>system</scope>
            <systemPath>${ezyplatform.home}/admin/plugins/ezyarticle/lib/ezyarticle-sdk-${ezyarticle.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezychat-sdk</artifactId>
            <version>${ezychat.version}</version>
            <scope>system</scope>
            <systemPath>${ezyplatform.home}/web/plugins/ezychat/lib/ezychat-sdk-${ezychat.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezyplatform-common</artifactId>
            <version>${ezy.platform.version}</version>
            <scope>system</scope>
            <systemPath>${ezyplatform.home}/lib/ezyplatform-common-${ezy.platform.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezyplatform-common-sdk</artifactId>
            <version>${ezy.platform.version}</version>
        <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezyplatform-socket-sdk</artifactId>
            <version>${ezy.platform.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>graphql-sdk</artifactId>
            <version>${graphql.version}</version>
            <scope>system</scope>
            <systemPath>${ezyplatform.home}/web/plugins/graphql/lib/graphql-sdk-${graphql.version}.jar</systemPath>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-checkstyle-plugin</artifactId>
                <version>${maven.checkstyle.plugin.version}</version>
                <dependencies>
                    <dependency>
                        <groupId>com.puppycrawl.tools</groupId>
                        <artifactId>checkstyle</artifactId>
                        <version>8.42</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <consoleOutput>true</consoleOutput>
                    <violationSeverity>warning</violationSeverity>
                    <configLocation>checkstyle.xml</configLocation>
                </configuration>
                <executions>
                    <execution>
                        <id>verify</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
