#
 # Copyright 2026 youngmonkeys.org
 # 
 # Licensed under the ezyplatform, Version 1.0.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 # 
 #     https://youngmonkeys.org/licenses/ezyplatform-1.0.0.txt
 # 
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
#

top.ezyvector=/; fas fa-vector-square
top.ezyvector.data_chunks=/data-chunks; fas fa-th-large
top.ezyvector.embedding_services=/embedding-services; fas fa-stream
top.ezyvector.embedding_services_details=~/embedding-services/{serviceName}
top.ezyvector.vector_database_services=/vector-database-services; fas fa-database
top.ezyvector.vector_database_services_details=~/vector-database-services/{serviceName}
top.ezyvector.settings=/settings; fas fa-tools
