<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
 ~ Copyright 2026 youngmonkeys.org
 ~ 
 ~ Licensed under the ezyplatform, Version 1.0.0 (the "License");
 ~ you may not use this file except in compliance with the License.
 ~ You may obtain a copy of the License at
 ~ 
 ~     https://youngmonkeys.org/licenses/ezyplatform-1.0.0.txt
 ~ 
 ~ Unless required by applicable law or agreed to in writing, software
 ~ distributed under the License is distributed on an "AS IS" BASIS,
 ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 ~ See the License for the specific language governing permissions and
 ~ limitations under the License.
--><project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>org.youngmonkeys</groupId>
        <artifactId>ezyvector</artifactId>
        <version>0.0.1</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>ezyvector-admin-plugin</artifactId>
    <name>ezyvector-admin-plugin</name>
    <url>https://youngmonkeys.org</url>

    <dependencies>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezyplatform-admin-sdk</artifactId>
            <version>${ezy.platform.version}</version>
        </dependency>
        <!-- start add sdk dependency -->
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezyvector-sdk</artifactId>
            <version>${project.version}</version>
        </dependency>
        <!-- end add sdk dependency -->
        <dependency>
            <groupId>org.apache.pdfbox</groupId>
            <artifactId>pdfbox</artifactId>
            <version>${pdfbox.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
            <version>${poi.version}</version>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezyplatform-common</artifactId>
            <version>${ezy.platform.version}</version>
            <scope>system</scope>
            <systemPath>${ezyplatform.home}/lib/ezyplatform-common-${ezy.platform.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezyplatform-admin</artifactId>
            <version>${ezy.platform.version}</version>
            <scope>system</scope>
            <systemPath>${ezyplatform.home}/admin/lib/ezyplatform-admin-${ezy.platform.version}.jar</systemPath>
        </dependency>
    <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ecommerce-admin-plugin</artifactId>
            <version>${ecommerce.version}</version>
            <scope>system</scope>
            <systemPath>
                ${ezyplatform.home}/admin/plugins/ecommerce/lib/ecommerce-admin-plugin-${ecommerce.version}.jar
            </systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ecommerce-sdk</artifactId>
            <version>${ecommerce.version}</version>
            <scope>system</scope>
            <systemPath>
                ${ezyplatform.home}/admin/plugins/ecommerce/lib/ecommerce-sdk-${ecommerce.version}.jar
            </systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezyaccount-admin-plugin</artifactId>
            <version>${ezyaccount.version}</version>
            <scope>system</scope>
            <systemPath>${ezyplatform.home}/admin/plugins/ezyaccount/lib/ezyaccount-admin-plugin-${ezyaccount.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezyaccount-sdk</artifactId>
            <version>${ezyaccount.version}</version>
        <scope>system</scope>
            <systemPath>${ezyplatform.home}/admin/plugins/ezyaccount/lib/ezyaccount-sdk-${ezyaccount.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezyai-sdk</artifactId>
            <version>${ezyai.version}</version>
        <scope>system</scope>
            <systemPath>${ezyplatform.home}/admin/plugins/ezyai/lib/ezyai-sdk-${ezyai.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezyarticle-admin-plugin</artifactId>
            <version>${ezyarticle.version}</version>
            <scope>system</scope>
            <systemPath>${ezyplatform.home}/admin/plugins/ezyarticle/lib/ezyarticle-admin-plugin-${ezyarticle.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezyarticle-sdk</artifactId>
            <version>${ezyarticle.version}</version>
        <scope>system</scope>
            <systemPath>${ezyplatform.home}/admin/plugins/ezyarticle/lib/ezyarticle-sdk-${ezyarticle.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezychat-admin-plugin</artifactId>
            <version>${ezychat.version}</version>
            <scope>system</scope>
            <systemPath>${ezyplatform.home}/admin/plugins/ezychat/lib/ezychat-admin-plugin-${ezychat.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezychat-sdk</artifactId>
            <version>${ezychat.version}</version>
        <scope>system</scope>
            <systemPath>${ezyplatform.home}/admin/plugins/ezychat/lib/ezychat-sdk-${ezychat.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezycrm-admin-plugin</artifactId>
            <version>${ezycrm.version}</version>
            <scope>system</scope>
            <systemPath>${ezyplatform.home}/admin/plugins/ezycrm/lib/ezycrm-admin-plugin-${ezycrm.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezycrm-sdk</artifactId>
            <version>${ezycrm.version}</version>
        <scope>system</scope>
            <systemPath>${ezyplatform.home}/admin/plugins/ezycrm/lib/ezycrm-sdk-${ezycrm.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezylogin-admin-plugin</artifactId>
            <version>${ezylogin.version}</version>
            <scope>system</scope>
            <systemPath>${ezyplatform.home}/admin/plugins/ezylogin/lib/ezylogin-admin-plugin-${ezylogin.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezylogin-sdk</artifactId>
            <version>${ezylogin.version}</version>
            <scope>system</scope>
            <systemPath>${ezyplatform.home}/admin/plugins/ezylogin/lib/ezylogin-sdk-${ezylogin.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezymail-admin-plugin</artifactId>
            <version>${ezymail.version}</version>
            <scope>system</scope>
            <systemPath>${ezyplatform.home}/admin/plugins/ezymail/lib/ezymail-admin-plugin-${ezymail.version}.jar
            </systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezymail-sdk</artifactId>
            <version>${ezymail.version}</version>
            <scope>system</scope>
            <systemPath>${ezyplatform.home}/admin/plugins/ezymail/lib/ezymail-sdk-${ezymail.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezyplatform-test-sdk</artifactId>
            <version>${ezy.platform.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezysupport-admin-plugin</artifactId>
            <version>${ezysupport.version}</version>
            <scope>system</scope>
            <systemPath>${ezyplatform.home}/admin/plugins/ezysupport/lib/ezysupport-admin-plugin-${ezysupport.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezysupport-sdk</artifactId>
            <version>${ezysupport.version}</version>
        <scope>system</scope>
            <systemPath>${ezyplatform.home}/admin/plugins/ezysupport/lib/ezysupport-sdk-${ezysupport.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>graphql-admin-plugin</artifactId>
            <version>${graphql.version}</version>
            <scope>system</scope>
            <systemPath>${ezyplatform.home}/admin/plugins/graphql/lib/graphql-admin-plugin-${graphql.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>graphql-sdk</artifactId>
            <version>${graphql.version}</version>
        <scope>system</scope>
            <systemPath>${ezyplatform.home}/admin/plugins/graphql/lib/graphql-sdk-${graphql.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezyai-admin-plugin</artifactId>
            <version>${ezyai.version}</version>
            <scope>system</scope>
            <systemPath>${ezyplatform.home}/admin/plugins/ezyai/lib/ezyai-admin-plugin-${ezyai.version}.jar</systemPath>
        </dependency>
    </dependencies>
    <profiles>
        <profile>
            <id>test</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <build>
                <resources>
                    <resource>
                        <directory>src/main/resources</directory>
                    </resource>
                    <resource>
                        <directory>${ezyplatform.home}/settings</directory>
                    </resource>
                    <resource>
                        <directory>${ezyplatform.home}/admin/resources</directory>
                    </resource>
                    <resource>
                        <directory>${ezyplatform.home}/admin/settings</directory>
                    </resource>
                <resource>
                        <directory>${ezyplatform.home}/admin/plugins/ezyai/resources</directory>
                    </resource>
                <resource>
                        <directory>${ezyplatform.home}/admin/plugins/ezyarticle/resources</directory>
                    </resource>
                <resource>
                        <directory>${ezyplatform.home}/admin/plugins/ezychat/resources</directory>
                    </resource>
                <resource>
                        <directory>${ezyplatform.home}/admin/plugins/graphql/resources</directory>
                    </resource>
                <resource>
                        <directory>${ezyplatform.home}/admin/plugins/ecommerce/resources</directory>
                    </resource>
                <resource>
                        <directory>${ezyplatform.home}/admin/plugins/ezymail/resources</directory>
                    </resource>
                </resources>
            </build>
        </profile>
    </profiles>
</project>
