<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
 ~ Copyright 2026 youngmonkeys.org
 ~ 
 ~ Licensed under the ezyplatform, Version 1.0.0 (the "License");
 ~ you may not use this file except in compliance with the License.
 ~ You may obtain a copy of the License at
 ~ 
 ~     https://youngmonkeys.org/licenses/ezyplatform-1.0.0.txt
 ~ 
 ~ Unless required by applicable law or agreed to in writing, software
 ~ distributed under the License is distributed on an "AS IS" BASIS,
 ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 ~ See the License for the specific language governing permissions and
 ~ limitations under the License.
--><project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>ezyvector</artifactId>
        <groupId>org.youngmonkeys</groupId>
        <version>0.0.1</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>ezyvector-web-plugin</artifactId>
    <name>ezyvector-web-plugin</name>
    <url>https://youngmonkeys.org</url>

    <dependencies>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezyplatform-web-sdk</artifactId>
            <version>${ezy.platform.version}</version>
        </dependency>
        <!-- start add sdk dependency -->
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezyvector-sdk</artifactId>
            <version>${project.version}</version>
        </dependency>
        <!-- end add sdk dependency -->
        <dependency>
            <groupId>org.apache.pdfbox</groupId>
            <artifactId>pdfbox</artifactId>
            <version>${pdfbox.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
            <version>${poi.version}</version>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezyplatform-common</artifactId>
            <version>${ezy.platform.version}</version>
            <scope>system</scope>
            <systemPath>${ezyplatform.home}/lib/ezyplatform-common-${ezy.platform.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezyplatform-web</artifactId>
            <version>${ezy.platform.version}</version>
            <scope>system</scope>
            <systemPath>${ezyplatform.home}/web/lib/ezyplatform-web-${ezy.platform.version}.jar</systemPath>
        </dependency>
    <dependency>
            <groupId>com.google.api-client</groupId>
            <artifactId>google-api-client</artifactId>
            <version>${google.client.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.google.apis</groupId>
            <artifactId>google-api-services-oauth2</artifactId>
            <version>${google.apis.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.restfb</groupId>
            <artifactId>restfb</artifactId>
            <version>${facebook.client.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ecommerce-sdk</artifactId>
            <version>${ecommerce.version}</version>
        <scope>system</scope>
            <systemPath>${ezyplatform.home}/web/plugins/ecommerce/lib/ecommerce-sdk-${ecommerce.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ecommerce-web-plugin</artifactId>
            <version>${ecommerce.version}</version>
            <scope>system</scope>
            <systemPath>${ezyplatform.home}/web/plugins/ecommerce/lib/ecommerce-web-plugin-${ecommerce.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezyaccount-sdk</artifactId>
            <version>${ezyaccount.version}</version>
        <scope>system</scope>
            <systemPath>${ezyplatform.home}/web/plugins/ezyaccount/lib/ezyaccount-sdk-${ezyaccount.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezyaccount-web-plugin</artifactId>
            <version>${ezyaccount.version}</version>
            <scope>system</scope>
            <systemPath>${ezyplatform.home}/web/plugins/ezyaccount/lib/ezyaccount-web-plugin-${ezyaccount.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezyai-sdk</artifactId>
            <version>${ezyai.version}</version>
        <scope>system</scope>
            <systemPath>${ezyplatform.home}/web/plugins/ezyai/lib/ezyai-sdk-${ezyai.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezyarticle-sdk</artifactId>
            <version>${ezyarticle.version}</version>
        <scope>system</scope>
            <systemPath>${ezyplatform.home}/web/plugins/ezyarticle/lib/ezyarticle-sdk-${ezyarticle.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezyarticle-web-plugin</artifactId>
            <version>${ezyarticle.version}</version>
            <scope>system</scope>
            <systemPath>${ezyplatform.home}/web/plugins/ezyarticle/lib/ezyarticle-web-plugin-${ezyarticle.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezychat-sdk</artifactId>
            <version>${ezychat.version}</version>
        <scope>system</scope>
            <systemPath>${ezyplatform.home}/web/plugins/ezychat/lib/ezychat-sdk-${ezychat.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezychat-web-plugin</artifactId>
            <version>${ezychat.version}</version>
            <scope>system</scope>
            <systemPath>${ezyplatform.home}/web/plugins/ezychat/lib/ezychat-web-plugin-${ezychat.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezycrm-sdk</artifactId>
            <version>${ezycrm.version}</version>
        <scope>system</scope>
            <systemPath>${ezyplatform.home}/web/plugins/ezycrm/lib/ezycrm-sdk-${ezycrm.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezycrm-web-plugin</artifactId>
            <version>${ezycrm.version}</version>
            <scope>system</scope>
            <systemPath>${ezyplatform.home}/web/plugins/ezycrm/lib/ezycrm-web-plugin-${ezycrm.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezylogin-sdk</artifactId>
            <version>${ezylogin.version}</version>
            <scope>system</scope>
            <systemPath>${ezyplatform.home}/web/plugins/ezylogin/lib/ezylogin-sdk-${ezylogin.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezylogin-web-plugin</artifactId>
            <version>${ezylogin.version}</version>
            <scope>system</scope>
            <systemPath>${ezyplatform.home}/web/plugins/ezylogin/lib/ezylogin-web-plugin-${ezylogin.version}.jar
            </systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezymail-sdk</artifactId>
            <version>${ezymail.version}</version>
            <scope>system</scope>
            <systemPath>${ezyplatform.home}/web/plugins/ezymail/lib/ezymail-sdk-${ezymail.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezymail-web-plugin</artifactId>
            <version>${ezymail.version}</version>
            <scope>system</scope>
            <systemPath>${ezyplatform.home}/web/plugins/ezymail/lib/ezymail-web-plugin-${ezymail.version}.jar
            </systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezyplatform-test-sdk</artifactId>
            <version>${ezy.platform.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezysupport-sdk</artifactId>
            <version>${ezysupport.version}</version>
        <scope>system</scope>
            <systemPath>${ezyplatform.home}/web/plugins/ezysupport/lib/ezysupport-sdk-${ezysupport.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezysupport-web-plugin</artifactId>
            <version>${ezysupport.version}</version>
            <scope>system</scope>
            <systemPath>${ezyplatform.home}/web/plugins/ezysupport/lib/ezysupport-web-plugin-${ezysupport.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>graphql-sdk</artifactId>
            <version>${graphql.version}</version>
        <scope>system</scope>
            <systemPath>${ezyplatform.home}/web/plugins/graphql/lib/graphql-sdk-${graphql.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>graphql-web-plugin</artifactId>
            <version>${graphql.version}</version>
            <scope>system</scope>
            <systemPath>${ezyplatform.home}/web/plugins/graphql/lib/graphql-web-plugin-${graphql.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezyai-web-plugin</artifactId>
            <version>${ezyai.version}</version>
            <scope>system</scope>
            <systemPath>${ezyplatform.home}/web/plugins/ezyai/lib/ezyai-web-plugin-${ezyai.version}.jar</systemPath>
        </dependency>
    </dependencies>
    <profiles>
        <profile>
            <id>test</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <build>
                <resources>
                    <resource>
                        <directory>src/main/resources</directory>
                    </resource>
                    <resource>
                        <directory>${ezyplatform.home}/settings</directory>
                    </resource>
                    <resource>
                        <directory>${ezyplatform.home}/web/resources</directory>
                    </resource>
                    <resource>
                        <directory>${ezyplatform.home}/web/settings</directory>
                    </resource>
                <resource>
                        <directory>${ezyplatform.home}/web/plugins/ezyai/resources</directory>
                    </resource>
                <resource>
                        <directory>${ezyplatform.home}/web/plugins/ezyarticle/resources</directory>
                    </resource>
                <resource>
                        <directory>${ezyplatform.home}/web/plugins/ezychat/resources</directory>
                    </resource>
                <resource>
                        <directory>${ezyplatform.home}/web/plugins/graphql/resources</directory>
                    </resource>
                <resource>
                        <directory>${ezyplatform.home}/web/plugins/ecommerce/resources</directory>
                    </resource>
                <resource>
                        <directory>${ezyplatform.home}/web/plugins/ezymail/resources</directory>
                    </resource>
                </resources>
            </build>
        </profile>
    </profiles>
</project>
